In [1]:
import pandas as pd

In [2]:
# Cleaning Data
raw_data=pd.read_csv("raw_data.csv")
raw_data
cleaned_data=raw_data.copy()

In [5]:
# 1-> Handle Missing Values

# isnull() / isna() => Returns True if value is not present and returns False when value is present.
raw_data.isnull()
raw_data.isna()


# isnull().sum() => We can count the missing values in every column 
raw_data.isnull().sum()
raw_data.isna().sum()


# dropna() => It drop the row/rows with even a one single null value 
raw_data.dropna()
raw_data.dropna(axis=1)


# fillna() => We can fill the null values with a particular value
raw_data.fillna(0)
cleaned_data["age"]=cleaned_data["age"].fillna(cleaned_data["age"].mean())    # Here we filled the null values in age column with the mean of the remaining values of age in that column
cleaned_data


# ffill() => Forward Fill => If we are reading any column from up to down and if there is any missing value then in that cell the value of previous cell in column will be used to read that column
raw_data.ffill()


# bfill() => Backward FIll => If we are reading any column from down to up and if there is any missing value then in that cell the value of previous cell in column will be used to read that column
raw_data.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [9]:
# 2-> Handle Duplicated Values

# duplicated() => 

raw_data.duplicated()
raw_data[["country","gender"]].duplicated()
raw_data.drop_duplicates()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [22]:
# 3-> Handle Data Types & Date-Time

# dtypes() => It is used to check data type of every coulmn
raw_data.dtypes

# astype(newType) => If we want to change data type of any column
temp_data = raw_data.copy()
temp_data=temp_data.fillna(0)
temp_data["age"]=temp_data["age"].astype("int64")
temp_data.dtypes

# to_datetime() => If we want to convert normal data into date time data in pandas then we use it.
aqi_data=pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"].dtypes   # It will give Object data type as output
aqi_data["timestamp"]=pd.to_datetime(aqi_data["timestamp"])     # TO convert its data type to the datetime data type
aqi_data["timestamp"].dtypes

dtype('<M8[ns]')

In [35]:
# 4-> Handle Strings

# lower() => Converts all letters to the lower case
raw_data["gender"].str.lower()  

# upper() => Converts all letters to the upper case
raw_data["gender"].str.upper()  

# capitalize() => Converts first word of every letter to the upper case
raw_data["gender"].str.capitalize()  

# strip() => Removes extra spaces 


# split() => We can split our character on the basis of word in different parts
raw_data["name"].str.split(" ")    # separate on the basis of spacing 

# contains() =>  checks wether particular thing exists in the string
raw_data["country"].str.contains("US")
raw_data["country"].str.contains("india",case=False)   # we ignore the cases here like upper, lower case

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object