In [14]:
import pandas as pd
import numpy as np

In [2]:
# DataFrame creation in differenet ways ....

In [11]:
# 1-> Dictionary of lists

info={
    "Name":["Ayush","Luv","Aman"],
    "Age":[19,19,17],
    "CGPA":[7.8,7.6,9.1],
}

df=pd.DataFrame(info)
print(df,type(df))
df     # To visualize it more structurally.

print(df.index)    # To print label values of Row
print(df.columns)  # To print label values of Column

    Name  Age  CGPA
0  Ayush   19   7.8
1    Luv   19   7.6
2   Aman   17   9.1 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='object')

In [8]:
# 2-> List of lists

df=pd.DataFrame([["Ayush",19,7.8],["Luv",19,7.6],["Aman",17,9.1]],columns=["Name","Age","CGPA"]) # Here in List of Lists every list will become a single row and for column headers we had to pass those separately.
print(df,type(df))
df

    Name  Age  CGPA
0  Ayush   19   7.8
1    Luv   19   7.6
2   Aman   17   9.1 <class 'pandas.core.frame.DataFrame'>

    Name  Age  CGPA
0  Ayush   19   7.8
1    Luv   19   7.6
2   Aman   17   9.1

In [17]:
# 3-> Numpy Arrays

np_arr1=np.array([[1,2,3],[4,5,6]])     # Individual List in numpy array will become individual row
df1=pd.DataFrame(np_arr1)
print(df1,type(df1))



np_arr2=np.array([["Ayush",19,7.8],["Luv",19,7.6],["Aman",17,9.1]])
df2=pd.DataFrame(np_arr2,columns=["Name","Age","CGPA"])
print(df2,type(df2))
df2

   0  1  2
0  1  2  3
1  4  5  6 <class 'pandas.core.frame.DataFrame'>
    Name Age CGPA
0  Ayush  19  7.8
1    Luv  19  7.6
2   Aman  17  9.1 <class 'pandas.core.frame.DataFrame'>

    Name Age CGPA
0  Ayush  19  7.8
1    Luv  19  7.6
2   Aman  17  9.1