In [1]:
import pandas as pd

In [2]:
raw_data=pd.read_csv("raw_data.csv")
raw_data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [5]:
# Transforming Data or Feature Engineering

copy_data=raw_data.copy()

In [4]:
# 1->    apply() -> This function is used to add row/column , this function takes another function as the argument and that function whoch is passed as argument can be a logic .

copy_data["tax"]=copy_data["income"].apply(lambda x : "20%" if x>=50000 else "10%")    # logic is passed inside the apply function using lmabda function
copy_data

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  20%
1    1      John Doe  29.0     USA     Male  55000.0  20%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  20%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%

In [8]:
# 2->    map() -> It is used when we have to map existing values with the new values.

# for ex in the data We have to Male->M, Female->F, Unknown-> U

gender_map={"Male":"M","Female":"F","Unknown":"U"}
copy_data["gender"]=copy_data["gender"].map(gender_map)
copy_data

    id          name   age country gender   income
0    1      John Doe  29.0     USA      M  55000.0
1    1      John Doe  29.0     USA      M  55000.0
2    2    Jane Smith   NaN  Canada      F  62000.0
3    3          Alex   NaN     USA      U  47000.0
4    4  Maria Garcia  34.0   Spain      F      NaN
5    5        Li Wei  27.0   China      M  51000.0
6    6           NaN  45.0   India      F  73000.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0
8    8    Rachel Lee  29.0     USA      F  62000.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0
10  10   Emily Davis  31.0     USA    NaN  58000.0

In [10]:
# 3 ->      assign() -> To make new changes in the data 

copy_data.assign(new_income=copy_data["income"]*1.1)     # here we have created a new column new_income with exisiting income increased by 10%

    id          name   age country gender   income  new_income
0    1      John Doe  29.0     USA      M  55000.0     60500.0
1    1      John Doe  29.0     USA      M  55000.0     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0     68200.0
3    3          Alex   NaN     USA      U  47000.0     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN         NaN
5    5        Li Wei  27.0   China      M  51000.0     56100.0
6    6           NaN  45.0   India      F  73000.0     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0     63800.0

In [14]:
# 4 ->     replace(old,new) ->   It is used to replace some specific old values with some new values

copy_data["country"]=copy_data["country"].replace("USA","US")
copy_data

    id          name   age country gender   income
0    1      John Doe  29.0      US      M  55000.0
1    1      John Doe  29.0      US      M  55000.0
2    2    Jane Smith   NaN  Canada      F  62000.0
3    3          Alex   NaN      US      U  47000.0
4    4  Maria Garcia  34.0   Spain      F      NaN
5    5        Li Wei  27.0   China      M  51000.0
6    6           NaN  45.0   India      F  73000.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0
8    8    Rachel Lee  29.0      US      F  62000.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0
10  10   Emily Davis  31.0      US    NaN  58000.0

In [21]:
# 5 ->     rename(columns={old,new}) ->   It is used to rename the rows and columns.

copy_data.columns=["Id","Name","Age","Country","Gender","Income"]  # This is the Raw Way of renaming all the columns

copy_data.rename(columns={"Income":"Salary"})    # This is the way to rename a individual column
copy_data.rename(index={1:"First"})    # This is the way to rename a individual row

       Id          Name   Age Country Gender   Income
0       1      John Doe  29.0      US      M  55000.0
First   1      John Doe  29.0      US      M  55000.0
2       2    Jane Smith   NaN  Canada      F  62000.0
3       3          Alex   NaN      US      U  47000.0
4       4  Maria Garcia  34.0   Spain      F      NaN
5       5        Li Wei  27.0   China      M  51000.0
6       6           NaN  45.0   India      F  73000.0
7       7    Ahmed Khan  38.0     NaN      M  68000.0
8       8    Rachel Lee  29.0      US      F  62000.0
9       9   Carlos Ruiz   NaN  Mexico      M  45000.0
10     10   Emily Davis  31.0      US    NaN  58000.0

In [39]:
# 5 ->     sort_values() ->   It is used to sort row/column on the basis of the values in them 

copy_data["Income"].sort_values()  # This will sort the values into ascending order 

# OR    [You can write the above code as like this also]

copy_data.sort_values("Income")  # pandas preserves the original labels

copy_data.sort_values("Income",ascending=False)   # This will sort the values into descending order

sorted_copy_data=copy_data.sort_values(["Income","Age"])   # we can sort the values in two parameters so here sorting will be done on the basis of income but if two incomes are same then sorting will be performed on the basis of Age.

In [38]:
# 6 ->     sort_index() ->   It is used to sort index

# But if you will use it on the sorted data it will reverse the effect of sorting and original data wil be recieved.
sorted_copy_data.sort_index()

    Id          Name   Age Country Gender   Income
0    1      John Doe  29.0      US      M  55000.0
1    1      John Doe  29.0      US      M  55000.0
2    2    Jane Smith   NaN  Canada      F  62000.0
3    3          Alex   NaN      US      U  47000.0
4    4  Maria Garcia  34.0   Spain      F      NaN
5    5        Li Wei  27.0   China      M  51000.0
6    6           NaN  45.0   India      F  73000.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0
8    8    Rachel Lee  29.0      US      F  62000.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0
10  10   Emily Davis  31.0      US    NaN  58000.0

In [41]:
# 7 ->     reset_index() ->   It is used to reset index

# if you use it on the sorted data then that data will remain sorted and the original index will be preserved inside a new column named index but it will create a new label for each row that will start from 0.
sorted_copy_data.reset_index()

sorted_copy_data.reset_index(drop=True)  # Here data will remain sorted and pandas is trying to preserve original index but we don't want original index to be preserved so a new label for each row that will start from 0, without any column having original indices.

    Id          Name   Age Country Gender   Income
0    9   Carlos Ruiz   NaN  Mexico      M  45000.0
1    3          Alex   NaN      US      U  47000.0
2    5        Li Wei  27.0   China      M  51000.0
3    1      John Doe  29.0      US      M  55000.0
4    1      John Doe  29.0      US      M  55000.0
5   10   Emily Davis  31.0      US    NaN  58000.0
6    8    Rachel Lee  29.0      US      F  62000.0
7    2    Jane Smith   NaN  Canada      F  62000.0
8    7    Ahmed Khan  38.0     NaN      M  68000.0
9    6           NaN  45.0   India      F  73000.0
10   4  Maria Garcia  34.0   Spain      F      NaN